version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    # Disable rebasing for npm pull requests
    rebase-strategy: 'disabled'
    open-pull-requests-limit: 10
