name: Tests
on: [pull_request]
jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - name: Fetch Node Packages
        run: |
          yarn --immutable
      - name: Display info
        run: |
          yarn run cypress info
      - name: Run tests
        run: |
          yarn serve & 
          yarn cypress:run --browser ${{ matrix.browser }}
      - name: Upload Recordings
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: cypress
          path: |
            cypress
            cypress-visual-screenshots
            cypress-visual-report
